name: calzone
author: Michael Bullington <mikebullingtn@gmail.com>
homepagehttps://github.com/DirectMyFile/calzone.dart: # https://github.com/user/repo
version: 0.1.0
environment:
  sdk: '>=1.10.0 <2.0.0'
description: Use Dart libraries from JavaScript.
