name: calzone
author: Michael Bullington <mikebullingtn@gmail.com>
homepage: https://github.com/DirectMyFile/calzone.dart
version: 0.1.0
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  analyzer: '^0.25.0+1'
  path: '^1.3.5'
  node_preamble: '^1.0.0'
  analysis:
    git: https://github.com/mbullington/analysis.git
dev_dependencies:
  test: '>=0.12.3+4 <0.13.0'
description: Use Dart libraries from JavaScript.
