name: calzone
version: 0.1.5
description: Use Dart libraries from JavaScript.
authors:
  - Michael Bullington <m.bullington@dglogik.com>
  - Kenneth Endfinger <k.endfinger@dglogik.com>
homepage: https://github.com/dglogik/calzone.dart
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  analyzer: '^0.25.0+1'
  path: '^1.3.5'
  node_preamble: '^1.0.0'
  calzone_analysis:
    git: https://github.com/mbullington/analysis.git
    # path: ../analysis
dev_dependencies:
  test: '>=0.12.3+4 <0.13.0'
